#!/bin/bash
VERSION=0.9.7
RUBY_VERSION=1.9.2-p136
RUBYGEMS_VERSION=1.4.1
SQLITE_VERSION=3070400
SCITE_VERSION=223

SOURCE_DIR="$PWD"
TARGET_DIR="$HOME/easy-rails"
DOWNLOAD_DIR="$HOME/easy-rails-downloads"

RUBY_HOME="$TARGET_DIR/ruby"
GEM_OPTIONS="--no-ri --no-rdoc"
PATH="$TARGET_DIR/ruby/bin":"$PATH"

